[workspace]
channels = ["https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "BIONIX_ML_VIVAZ"
platforms = ["linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[dependencies]
mojo = "==0.25.6"
#bionix_ml = { path = "../../BIONIX-ML" }

[tasks]
executar = "mojo -I ../../BIONIX-ML principal.mojo"
compilar = { cmd = "mkdir -p build && mojo build -I ../../BIONIX-ML -o build/principal principal.mojo" }

# Execuções e compilações dos modos principais
treinar_detector = "mojo -I ../../BIONIX-ML treino_detector.mojo"
compilar_treinar_detector = { cmd = "mkdir -p build && mojo build -I ../../BIONIX-ML -o build/treino treino_detector.mojo" }
api = "mojo -I ../../BIONIX-ML src/servico_api.mojo"
compilar_api = { cmd = "mkdir -p build && mojo build -I ../../BIONIX-ML -o build/poc src/servico_api.mojo" }
