[workspace]
channels = ["https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "BIONIX_ML_VIVAZ"
platforms = ["linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[dependencies]
mojo = "==0.25.6"
#bionix_ml = { path = "../../BIONIX-ML" }

[tasks]
executar = "mojo -I ../../BIONIX-ML principal.mojo"
compilar = { cmd = "mkdir -p build && mojo build -I ../../BIONIX-ML -o build/principal principal.mojo" }

# Execuções e compilações dos modos principais
api = "mojo -I ../../BIONIX-ML src/servico_api.mojo"
compilar_api = { cmd = "mkdir -p build && mojo build -I ../../BIONIX-ML -o build/poc src/servico_api.mojo" }
run_retina_train = "mojo -I ../../BIONIX-ML run_retina_train.mojo"
run_retina_infer = "mojo -I ../../BIONIX-ML run_retina_infer.mojo"
run_retina_train_debug_build = { cmd = "mojo build -debug-level=line-tables -I ../../BIONIX-ML -o ./run_retina_train run_retina_train.mojo" }
run_retina_train_debug_run = { cmd = "./run_retina_train" }
compilar_debug = { cmd = "mkdir -p build && mojo build -debug-level=line-tables -I ../../BIONIX-ML -o build/principal_debug principal.mojo" }